language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
after_success:
  - julia -e 'cd(Pkg.dir("CartesianGP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("CartesianGP"); Pkg.test("CartesianGP"; coverage=true)'
